apiVersion: v1
kind: Service
metadata:
  name: nginxapp
  namespace: devops-tools
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: nginxapp
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxapp
  namespace: devops-tools
  name: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - image: $nameImage
        imagePullPolicy: IfNotPresent
        name: nginxapp
        ports:
          - containerPort: 80